//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AoC01_01.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AoC01_01.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -1
        ///-19
        ///-7
        ///-2
        ///-3
        ///+9
        ///-17
        ///+19
        ///+3
        ///+16
        ///+7
        ///-2
        ///+5
        ///+10
        ///-1
        ///+17
        ///-4
        ///+16
        ///+10
        ///-2
        ///+6
        ///-2
        ///-18
        ///+7
        ///-3
        ///+1
        ///+18
        ///-13
        ///+15
        ///-6
        ///+5
        ///-15
        ///-17
        ///-16
        ///+7
        ///+1
        ///-17
        ///-17
        ///-15
        ///+19
        ///+1
        ///+20
        ///+11
        ///-4
        ///+13
        ///-16
        ///-22
        ///-19
        ///-2
        ///-18
        ///+3
        ///+3
        ///+8
        ///-19
        ///-10
        ///+7
        ///-13
        ///-7
        ///+16
        ///-18
        ///-5
        ///-6
        ///+3
        ///-7
        ///-6
        ///-7
        ///+3
        ///-17
        ///-8
        ///+14
        ///-13
        ///+1
        ///-13
        ///-7
        ///+14
        ///-12
        ///-12
        ///-5
        ///-13
        ///-18
        ///+5
        ///+4
        ///-7
        ///-18
        ///-10
        ///-8
        ///+7
        ///-15
        ///-2
        ///-3
        ///+6
        ///-11
        ///-14
        ///+4
        ///-18
        ///+6
        ///-12
        ///-4
        ///+5
        ///+1
        ///+15
        ///+5
        ///-7
        ///+15
        ///+18
        ///-8
        ///+16
        ///+5
        ///+12
        ///+21
        ///+19
        ///+18
        ///+5
        ///+5
        ///-4
        ///-2
        ///-2
        ///-7
        ///+18
        ///-16
        ///+15
        ///+12
        ///-6
        ///+10
        ///-14
        ///+3
        ///+9
        ///-15
        ///-2
        ///+13
        ///+7
        ///+17
        ///+13
        ///+16
        ///-7
        ///+22
        ///-18
        ///-7
        ///+15
        ///-3
        ///+18
        ///-7
        ///-3
        ///+4
        ///-10
        ///+14
        ///-1 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string input_AoC01 {
            get {
                return ResourceManager.GetString("input_AoC01", resourceCulture);
            }
        }
    }
}
